// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAvN6V2YcdGLdofBSWUE3qI_T8pklgTze4',
    appId: '1:781697375497:web:37f2050ff2d0f3368307d8',
    messagingSenderId: '781697375497',
    projectId: 'chat-app-69022',
    authDomain: 'chat-app-69022.firebaseapp.com',
    storageBucket: 'chat-app-69022.appspot.com',
    measurementId: 'G-2CDL4NRTR4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCj8y0tro6UQq7vNgHQcdyGtKjosxAxy4s',
    appId: '1:781697375497:android:2ccfdd5dca2ae9628307d8',
    messagingSenderId: '781697375497',
    projectId: 'chat-app-69022',
    storageBucket: 'chat-app-69022.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBG3YYqc6AVCZVz7_kRxcYZPl6MBdN-ygM',
    appId: '1:781697375497:ios:cfb8dbaa0aa3f9798307d8',
    messagingSenderId: '781697375497',
    projectId: 'chat-app-69022',
    storageBucket: 'chat-app-69022.appspot.com',
    androidClientId: '781697375497-j3d8f6n9jcub5uqjfgctp4l69gmbpg0r.apps.googleusercontent.com',
    iosClientId: '781697375497-vbocefmcpmsispacdodtroq7fm97aivr.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBG3YYqc6AVCZVz7_kRxcYZPl6MBdN-ygM',
    appId: '1:781697375497:ios:958fb3fdfa0622898307d8',
    messagingSenderId: '781697375497',
    projectId: 'chat-app-69022',
    storageBucket: 'chat-app-69022.appspot.com',
    androidClientId: '781697375497-j3d8f6n9jcub5uqjfgctp4l69gmbpg0r.apps.googleusercontent.com',
    iosClientId: '781697375497-fakbnnurnl8q3vji6u0ciutmkc68e29v.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatApp.RunnerTests',
  );
}
